function [len_trials,FramesPerSeq, stim_start_time, seq_period, stim_num, num_trials] = read_whiskerStimTxT(file_path)
%READ_WHISKERSTIMTXT Summary of this function goes here
%   Read info from the whisker_stim.txt file generated by LabView code.
fid = fopen(file_path,'rt');
txt = strings([8,1]);
iter = 1;
while true
    tline = fgetl(fid);
    if ~ischar(tline); break; end   %end of file
    txt(iter) = tline;
    iter = iter + 1;
end

len_trials = str2num(txt(2));
FramesPerSeq = str2num(txt(3));
stim_start_time = str2num(txt(4)) - 0.05;
seq_period = str2num(txt(5));
stim_num = str2num(txt(7));
num_trials = str2num(txt(8));

end


% Sample file example:
%{ 

Acquisition Settings:
80
12
2.450000
0.1600
Experimental Parameters:
20
120

%}
